### PR TITLE
remove useless comment, use black to fmt code, fix some warnings.

### PR DESCRIPTION
**Pull request by asukaminato0721**
There is something I am not sure about in PKGBUILD. I add FIXME to it. Help wanted.

Python file itself can be run on ArchLinux without a problem.

### CODE REVIEW

**Comment by sickcodes** [comment]
Hey this is great thanks for this :)

It's such a nice program, sorry for breaking it I think I attempted to upgrade gtk versions

**Comment by asukaminato0721** [comment]
Currently, there are some problems:

1. requirements.txt does not work properly. I haven't figured out how to fix it.
2. mouse location seems will keep running even stop recording.
3. when I close the window, the process does not stop.

Besides these, this works well.

**Comment by asukaminato0721** [comment]
I don't know how to continue fix it. Since it works well now.

About requirements:

1. https://pypi.org/project/PyGObject/
2. `gobject-introspection` is not from pypi https://pygobject.readthedocs.io/en/latest/getting_started.html?highlight=introspection#arch-logo-arch-linux
3. https://stackoverflow.com/a/44214237/13040423 says that `python3-gi` to be `pgi`, but https://github.com/pygobject/pgi says [Unmaintained: Use PyGObject instead]
4. https://pygobject.readthedocs.io/en/latest/getting_started.html?highlight=gir1.2#ubuntu-logo-ubuntu-debian-logo-debian  says that `gir1.2-gtk-3.0` is not from pypi.

**Comment by sickcodes** [comment]
Amazing, do you want to maintain the AUR package with me? I may ask to maintain feel free

**Pull request merged**
